# Generated by Django 4.0.2 on 2022-02-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='descricao',
            field=models.CharField(help_text='Descrição do Documento', max_length=100),
        ),
    ]
